spring.application.name=microservicesKafka
server.port=8081

# Eureka
eureka.client.restclient.enabled=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=cineleo-notificacoes
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Serviços externos
services.notification.url=http://localhost:8000