spring.application.name=eventos-service
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.restclient.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5434/eventos_db
spring.datasource.username=eventos_user
spring.datasource.password=eventos_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo

services.usuarios.url=http://localhost:8083
services.pagamento.url=http://localhost:5000

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}