spring.application.name=avaliacoes-service
server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.restclient.enabled=true

spring.data.mongodb.uri=mongodb://avaliacoes_user:avaliacoes_pass@localhost:27017/avaliacoes_db?authSource=avaliacoes_db


spring.security.oauth2.resourceserver.jwt.jwks-uri=http://localhost:8083/.well-known/jwks.json


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo


management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}


management.tracing.sampling.probability=1.0
management.tracing.propagation.type=w3c

management.otlp.metrics.export.enabled=false
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

management.opentelemetry.resource-attributes.service.name=${spring.application.name}
management.opentelemetry.resource-attributes.service.namespace=cineleo
management.opentelemetry.resource-attributes.deployment.environment=local

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.cineleo.avaliacoes=DEBUG
logging.level.io.opentelemetry.exporter.internal.http=OFF
