spring.application.name=avaliacoes-service
server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.restclient.enabled=true

spring.data.mongodb.uri=mongodb://avaliacoes_user:avaliacoes_pass@localhost:27017/avaliacoes_db?authSource=avaliacoes_db

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=avaliacoes-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*


spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.security.oauth2.resourceserver.jwt.jwks-uri=http://localhost:8083/.well-known/jwks.json


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo


management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}


avaliacao.prazo-edicao-horas=48
avaliacao.max-denuncias-revisao=5

management.tracing.sampling.probability=1.0
management.tracing.propagation.type=w3c

management.otlp.metrics.export.enabled=false
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

management.opentelemetry.resource-attributes.service.name=${spring.application.name}
management.opentelemetry.resource-attributes.service.namespace=cineleo
management.opentelemetry.resource-attributes.deployment.environment=local

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.cineleo.avaliacoes=DEBUG
logging.level.io.opentelemetry.exporter.internal.http=OFF
