spring.application.name=paymentService
server.port=5000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

asaas.api.url=https://sandbox.asaas.com/api/v3
asaas.api.key=$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjdmMTZlODJmLTc0Y2ItNDc2NC1iMTI0LWNjMjFjNDA0NjI0MTo6JGFhY2hfMjZmZDRhNzItNGY1Ny00Yjc2LTkyNzEtNGVmNmFjN2I5NGVi
notification.api.url=http://notification-service:8000