spring.application.name=paymentService
server.port=5000

# Asaas - paymentService
asaas.api.url=https://sandbox.asaas.com/api/v3
asaas.api.key=$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjAzM2IzYjkwLWVlN2UtNDFjZC04Y2VkLTE4NWRiYmE5M2RhODo6JGFhY2hfMzJiYjBmYzYtOGY3Mi00NjQwLTlmZjQtZWM3OGQ0NDA5NWMy