spring.application.name=usuarios-service
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

server.port=8083

spring.datasource.url=jdbc:postgresql://postgres-usuarios:5432/usuarios_db
spring.datasource.username=usuarios_user
spring.datasource.password=usuarios_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo
